name: Code Format Check

on:
  push:
    branches:
      - master  # 替换为你的默认分支或者其他你希望触发的分支

jobs:
  checkstyle:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install dependencies
      working-directory: backend/world-of-zuul
      run: mvn install

    - name: Run Checkstyle
      working-directory: backend/world-of-zuul
      run: mvn checkstyle:check
