name: Code Format Check

on:
  push:
    branches:
      - master  # 替换为你的默认分支或者其他你希望触发的分支

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # 设置你的 Java 版本，可以根据实际需要调整

      - name: Run Checkstyle
        run: 
          cd backend/world-of-zuul
          mvn clean verify --fail-never  # 执行 Maven 构建并运行 Checkstyle 检查

      - name: Fail on errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Code format check failed. Please fix the errors."
            exit 1
          fi
